services:
  - type: web
    name: grampanchayat-portal
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DB_DIR
        value: /opt/render/project/src/backend/data_persistence/db
      - key: UPLOADS_DIR
        value: /opt/render/project/src/backend/data_persistence/uploads
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/data_persistence
      sizeGB: 1
